// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbiKdmrNLjxt8BbUPVBSvzXzROFvzRqug',
    appId: '1:1017300834595:ios:496a1e99b8fe9f37721496',
    messagingSenderId: '1017300834595',
    projectId: 'grocerylist-1d885',
    databaseURL: 'https://grocerylist-1d885-default-rtdb.firebaseio.com',
    storageBucket: 'grocerylist-1d885.firebasestorage.app',
    iosBundleId: 'com.simmi.grocerylist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqJiIxEWGCjxfHKnH42_Bu25HkZ3Cgmqc',
    appId: '1:1017300834595:web:9a4744517c02ec30721496',
    messagingSenderId: '1017300834595',
    projectId: 'grocerylist-1d885',
    authDomain: 'grocerylist-1d885.firebaseapp.com',
    databaseURL: 'https://grocerylist-1d885-default-rtdb.firebaseio.com',
    storageBucket: 'grocerylist-1d885.firebasestorage.app',
    measurementId: 'G-KL7QKH5J2L',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqJiIxEWGCjxfHKnH42_Bu25HkZ3Cgmqc',
    appId: '1:1017300834595:web:12c0e261f128db65721496',
    messagingSenderId: '1017300834595',
    projectId: 'grocerylist-1d885',
    authDomain: 'grocerylist-1d885.firebaseapp.com',
    databaseURL: 'https://grocerylist-1d885-default-rtdb.firebaseio.com',
    storageBucket: 'grocerylist-1d885.firebasestorage.app',
    measurementId: 'G-JMYJRD0FE0',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbiKdmrNLjxt8BbUPVBSvzXzROFvzRqug',
    appId: '1:1017300834595:ios:f365e643bd11f5e9721496',
    messagingSenderId: '1017300834595',
    projectId: 'grocerylist-1d885',
    databaseURL: 'https://grocerylist-1d885-default-rtdb.firebaseio.com',
    storageBucket: 'grocerylist-1d885.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWOr3QiHZ4GNXsip3vEH8Krx3MihFzrbg',
    appId: '1:1017300834595:android:0acc9a9dabe9124c721496',
    messagingSenderId: '1017300834595',
    projectId: 'grocerylist-1d885',
    databaseURL: 'https://grocerylist-1d885-default-rtdb.firebaseio.com',
    storageBucket: 'grocerylist-1d885.firebasestorage.app',
  );

}